### PR TITLE
Defer chart init

### PR DESCRIPTION
**Pull request by trungleduc**

### CODE REVIEW

**Comment by trungleduc** [comment]
@dfguerrerom  could you confirm this PR fixes your issue in Voila? I tested it in JupyterLab and it works well

**Comment by dfguerrerom** [comment]
Thanks!, yes, it works in both jupyterlab and voila :)

The only thing is that if you resize the screen when the element is hidden or not in the window view, it won't be resized when it shows up, but yest, that was what you fixed here...  but at least it doesn't get squished.

https://github.com/user-attachments/assets/02fd2fa0-f762-4deb-9ead-1e622531e17b

> @dfguerrerom could you confirm this PR fixes your issue in Voila? I tested it in JupyterLab and it works well

**Comment by trungleduc** [comment]
> Thanks!, yes, it works in both jupyterlab and voila :)
> 
> The only thing is that if you resize the screen when the element is hidden or not in the window view, it won't be resized when it shows up again, but yest, that was what you fixed here... but at least it doesn't get squished.
> 
>  Screencast.from.02-10-2024.11.33.43.webm 
> > @dfguerrerom could you confirm this PR fixes your issue in Voila? I tested it in JupyterLab and it works well

This issue is the problem with the windowing renderer of JupyterLab. It does not work well with widgets. I don't get why JupyterLab developers decided to make this option default

**Comment by trungleduc** [comment]
This is a signal to detect if the cell is in the viewport. We might use this signal to resize the widgets when it is scrolled to.
https://jupyterlab.readthedocs.io/en/latest/developer/performance.html#viewport-state

**Comment by trungleduc** [comment]
Releasing a new version.

**Comment by dfguerrerom** [comment]
thanks a lot!!! yes... in any case this is not a big deal :).

**Comment by trungleduc** [comment]
it's out https://github.com/trungleduc/ipecharts/releases/tag/v1.0.8

**Pull request merged**
