### PR TITLE
feat: add style config

### LINKED ISSUE #9: How to change the default height of the echart widget?
I need to create a 150px height bar chart, but I saw that even though I can edit the `grid` property, there's a default css class applied to all the widgets with a `500px` height, so the widget container will remain with its default size while the chart will use the given height.

I tried doing `my_chart.add_class('new_height_class')`, but I also noticed that  the `update_classes` method doesn't `resize()` the chart, so I have to change the window size to make this change to happen.
Ideally I would like to achieve two things, pass a `class_` property to the `ECharstWidget()`,  and, trigger a `resize()` event after a new css class has added/removed.

I have already edited the `ECharts`... classes to trigger the resize when the css classes change, but I cannot make the initial state to change... would you mind to review a PR? or giving me any clue?

### PR DESCRIPTION
**Pull request by dfguerrerom**
Aims to close #9 

- Add style configuration as parameter
- Trigger resize event after classes have been edited

@trungleduc, please let me know if there's anything else to modify or if you approve the changes.

### CODE REVIEW

**Comment by trungleduc** [comment]
Thanks! It looks neat! Could you add a usage example to the readme?

**Comment by dfguerrerom** [comment]
> Thanks! It looks neat! Could you add a usage example to the readme?

Sure, I have updated the readme and added a new video... if you approve, can we merge and later replace the broken image link with the video url?

**Comment by trungleduc** [comment]
> > Thanks! It looks neat! Could you add a usage example to the readme?
> 
> Sure, I have updated the readme and added a new video... if you approve, can we merge and later replace the broken image link with the video url?

Sure!

**Review by trungleduc — APPROVED** [review]

**Comment by trungleduc** [comment]
Thanks!

**Comment by trungleduc** [comment]
released in 1.0.7

**Pull request merged**
